### ISSUE TITLE
Can't save a screenshot with selenium webdriver

### ISSUE THREAD

**Issue by tjoooobooo** [getgauge/gauge-ts#123]
**Describe the bug**
I'm trying to implement the CustomScreenshotWriter with gauge-ts and selenium but it doesn't work. It saves the screenshot but I suppose gauge requires an Uint8Array as the screenshot file but selenium does return a string as the screenshot.
So if I run the code I only get the output a.charCodeAt() is not a function. 

**To Reproduce**
1. Install gauge-ts
2. Install selenium-webdriver
3. Use given function for screenshots

```
 @CustomScreenshotWriter()
    public async takeScreenshot(): Promise<string> {

        return WebDriverManager.call(driver => {
            return new Promise((resolve, reject) => {

                driver.takeScreenshot()
                    .then(screenshot => {
                        let screenShotFilePath = join(
                            process.env['gauge_screenshots_dir'],
                            `screenshot-${v4()}.png`
                        );

                        writeFileSync(screenShotFilePath, screenshot);
                        resolve(basename(screenShotFilePath));
                    })
                    .catch(err => reject(err))
                ;
            });
        });
    }
```

**Desktop (please complete the following information):**
 - OS: linux
 - Gauge and plugin version [run `gauge -v`]
```
Gauge version: 1.1.5
Commit Hash: f455126

Plugins
-------
html-report (4.0.12)
js (2.3.14)
json-report (0.3.5)
screenshot (0.0.1)
ts (0.1.0)
```
 - Node version [run `node -v`]
```
v14.15.1
```
 - Npm version [run `npm -v`]
```
6.14.8
```

**Comment by BugDiver** [comment]
Method implementing ` CustomScreenshotWriter` should return a file path (string). Now how the file is created it's totally up to you

**Comment by tjoooobooo** [comment]
If I change to following code like that: 
```
let screenShotFilePath = join(
process.env['gauge_screenshots_dir'],
`screenshot-${v4()}.png`
);

writeFileSync(screenShotFilePath, screenshot);
_**resolve(screenShotFilePath);**_
```

the file path will be returned, but the test step output in console only is:
```
 Error Message: a.charCodeAt is not a function
        Stacktrace:
```

**Comment by BugDiver** [comment]
Could you please provide a sample project which can be used to replicate
the issue?
