### ISSUE TITLE
Website bugdiver.dev not up anymore

### ISSUE THREAD

**Issue by rose-m** [getgauge/gauge-ts#163]
Did the project's documentation move to a different URL? I'd be interested in using it but https://bugdiver.dev/ does not exist as a domain anymore.

**Comment by BugDiver** [comment]
@rose-m Seems like some issue with domain. Will look into it asap,
Meanwhile you can use https://github.com/BugDiver/gauge-ts/blob/main/docs/index.md to refer to documentation

**Comment by rose-m** [comment]
Awesome - thank you! :)
