### ISSUE TITLE
[0.3.4] "100% Invoiced" is omitting everything after `%`

### ISSUE THREAD

**Issue by mholetzko** [getgauge/gauge-ts#187]
**Describe the bug**

With 0.3.4 we see a bunch of issues on our test-suites. If we parse e.g. `100% Invoiced` to a step variable, then the parsed result is `100` instead of the whole string `100% Invoiced`.

This snippet shows the "issue" with the parseFloat implementation

```
const num1 = Number.parseFloat("100% Invoiced");
const num2 = Number("100% Invoiced")

// Expectation
console.log(Number.isNaN(num1)); -> False -> 100 -> Gauge parses as 100
console.log(Number.isNaN(num2)); -> True -> NaN -> Gauge parses as string as expected
```

> We can henceforth not use version 0.3.4. If I find some time, I can imagine writing up a few more detailed requirements, test cases and implement it, but won't be possible in the next days :) 

@lbockstaller

**Comment by zabil** [comment]
Closing for now. Will re-open if info about steps and implementation and versions are provided.

**Comment by mholetzko** [comment]
Hey @zabil ,

I was on vacation - I'll try to extract an example incl. versions soon.
We have reverted the versions so there is no pressure on our side. 

Will post here once I get to it - thanks for the quick reply though!

**Comment by kiranpatil-ic** [comment]
Seeing the same issue after upgrading to 1.3.4. Here are few details

Gauge version: 1.6.7
Plugins
-------
```
html-report (4.3.1)
screenshot (0.3.0)
ts (0.3.4)
xml-report (0.5.1)
```

Here is an example 

```
    @Step("Set filter to <commaSeparatedFilterValues>")
    async setFilter(commaSeparatedFilterValues: string) {
      console.log(`${commaSeparatedFilterValues} - ${typeof(commaSeparatedFilterValues)}`);
    }
```

```
* Set filter to "4578"

* Set filter to "4578 - 101"

* Set filter to "a4578"
```

**`---Output---`**
```
4578 - number
4578 - number
a4578 - string
```

As you can see above, if the step parameter is a number or begins with a numeric value, then the type of the parameter is number & any string value which follows the number is ignored. Downgrading to 0.3.3 works as expected.

@zabil  Please make sure your package.json has the same version i.e 0.3.4 in the dependencies for you to reproduce this issue.

**Comment by hazzik** [comment]
Having the same issue with phone numbers :-(

**Comment by zabil** [comment]
Planning to spend some time on this. Can you give me an example of the phone number format with this issue? (please use a fake number)

**Comment by zabil** [comment]
Fixed via https://github.com/getgauge/gauge-ts/pull/191
